# Generated by Django 4.1.7 on 2023-03-11 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('role', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='schools',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'schools',
            },
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=2000)),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('class_name', models.CharField(max_length=5)),
                ('section', models.CharField(max_length=2)),
                ('admissionid', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('guardian_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='smsapp.login')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('staff_id', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('joined_date', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='smsapp.login')),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='results',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_score', models.IntegerField()),
                ('obtained_score', models.IntegerField()),
                ('grade', models.CharField(default='', max_length=2)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smsapp.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smsapp.subject')),
            ],
            options={
                'db_table': 'results',
            },
        ),
        migrations.AddField(
            model_name='login',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smsapp.schools'),
        ),
    ]
