# Generated by Django 4.1.7 on 2023-03-11 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0002_alter_results_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='school',
        ),
    ]
